CREATE TABLE Genders (
    GenderID INT PRIMARY KEY AUTO_INCREMENT,
    GenderName VARCHAR(255) NOT NULL
);

CREATE TABLE Categories (
    CategoryID INT PRIMARY KEY AUTO_INCREMENT,
    CategoryName VARCHAR(255) NOT NULL,
    GenderID INT NOT NULL,
    FOREIGN KEY (GenderID) REFERENCES Genders(GenderID) ON DELETE CASCADE
);

CREATE TABLE Subcategories (
    SubcategoryID INT PRIMARY KEY AUTO_INCREMENT,
    SubcategoryName VARCHAR(255) NOT NULL,
    CategoryID INT NOT NULL,
    GenderID INT NOT NULL,
    FOREIGN KEY (CategoryID) REFERENCES Categories(CategoryID) ON DELETE CASCADE,
    FOREIGN KEY (GenderID) REFERENCES Genders(GenderID) ON DELETE CASCADE
);

CREATE TABLE Materials (
    MaterialID INT PRIMARY KEY AUTO_INCREMENT,
    MaterialName VARCHAR(255) NOT NULL
);

CREATE TABLE Colors (
    ColorID INT PRIMARY KEY AUTO_INCREMENT,
    ColorName VARCHAR(255) NOT NULL,
    ColorCode VARCHAR(255) NOT NULL
);

CREATE TABLE Products (
    ProductID INT PRIMARY KEY AUTO_INCREMENT,
    ProductName VARCHAR(255) NOT NULL,
    SubcategoryID INT,
    MaterialID INT,
    GenderID INT,
    Price DECIMAL(10, 2) NOT NULL,
    Description TEXT,
    FOREIGN KEY (GenderID) REFERENCES Genders(GenderID) ON DELETE SET NULL,
    FOREIGN KEY (MaterialID) REFERENCES Materials(MaterialID) ON DELETE SET NULL,
    FOREIGN KEY (SubcategoryID) REFERENCES Subcategories(SubcategoryID) ON DELETE SET NULL
);



CREATE TABLE Sizes (
    SizeID INT PRIMARY KEY AUTO_INCREMENT,
    SizeName VARCHAR(50) NOT NULL  -- e.g., "S", "M", "L", "XL"
);


CREATE TABLE Images (
    ImageID INT PRIMARY KEY AUTO_INCREMENT,
    ProductID INT,
    ImageURL VARCHAR(255) NOT NULL,
    FOREIGN KEY (ProductID) REFERENCES Products(ProductID) ON DELETE CASCADE
);